

// los types describen lo que pasa en nuestra aplicacion, se utilizan en el action como en el reducer

// por ejemplo supongamos que vamos  a llenar el formulario de agregar bebida . cuando presionamos
// agregar se va a disparar una accion que puede ser AGREGAR_PRODUCTO, PERO TAMBIEN CUANDO SE GUARDAN
// EN UNA BASE DE DATOS AGREGAR PRODUCTO EXITO , O SI HAY UN ERROR TAMBIEN UN ERROR 


export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'; // CUANDO SE GUARDA CORRECTAMENTE EN LA BASE DE DATOS
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';
export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTO_EXITO = ' DESCARGA_PRODUCTO_EXITO';
export const DESCARGA_PRODUCTO_ERROR = 'DESCARGA_PRODUCTO_ERROR';




export const OBTENER_PRODUCTO_ELIMINAR='OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO= 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';




export const OBTENER_PRODUCTO_EDITAR='OBTENER_PRODUCTO_EDITAR';
export const PRODUCTO_EDITADO_EXITO= 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';





// ESTOS TYPES SE UTILIZAN EN EL ACTION PARA DE AHI IR DESCRIBIENDO E IR EJECUTANDO CIERTAS FUNCIONES
//PERO EN EL REDUCER VAMOS A EVALUAR CADA UNA DE ESTAS CONDICIONES Y NOS VAN A SERVIR PARA MODIFICAR EL STATE
// DE ACUERDO A LO QUE ESTE SUCECIENDO , SE IMPORTAN EN EL REDUCER , EN ESTE CASO EN BebidasReducer.js